# Generated by Django 2.1.5 on 2019-03-26 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(default='MMC2573', max_length=10)),
                ('delivary_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('patient_age', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=50)),
                ('speciman_type', models.CharField(max_length=50)),
                ('ref_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_name', models.CharField(default='Test', max_length=30)),
                ('test_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('normal_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upto_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('address', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('speciman_type', models.CharField(max_length=20)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dataBaseApp.Worker')),
                ('test_report', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Test'),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Patient'),
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Patient'),
        ),
        migrations.AddField(
            model_name='report',
            name='ref_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Test'),
        ),
        migrations.AddField(
            model_name='cashmemo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataBaseApp.Report'),
        ),
    ]
